### ISSUE TITLE
Using %PATH% to find net.exe is dangerous. Must use %SystemRoot%/System32/net.exe

### ISSUE THREAD

**Issue by IlyaBiryukov** [sindresorhus/is-admin#2]
There is a possibility that net.exe on PATH is not the right one. There is malware out there disguising as net.exe, see for example http://www.ehow.com/how_5179034_remove-netexe.html

A better solution would be to use the more specific path, %SystemRoot%/System32/net.exe

**Comment by sindresorhus** [comment]
Having malware on your machine makes everything dangerous though. I don't see how this is an issue specifically with this module. I could make a malware with a fake `del.exe` and put it in the %PATH%. Pretty much everything in %PATH% can be dangerous then.

**Comment by IlyaBiryukov** [comment]
This particular case is more dangerous, because is-admin has more chances to run elevated.
