### ISSUE TITLE
Incorrectly returns false since 2.1.0

### ISSUE THREAD

**Issue by bbeldame** [sindresorhus/is-admin#5]
`execa('fsutil', ['dirty', 'query', '%systemdrive%'])`
This line fail with a error code 1 even when running as admin.

I tested the actual code with the execa package at version 0.4.0 and this problem does not occur.

I did not found the root of the problem while looking at the execa source code.

I guess there are two solutions : downgrade the execa version or find the problem in the execa package.

What do you think ?

**Comment by sindresorhus** [comment]
It's because `execa@0.4` used to just run everything as a shell command on Windows. Later `execa` versions improved this to run the command directly, but I didn't realize it *has* to be run as a shell command to expand the environment variable.
